matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
      before_install:
        - cd java
      script:
        - mvn install -B -V
      deploy:
        provider: script
        skip_cleanup: true
        script: cd $TRAVIS_BUILD_DIR && bash build-resources/travis-release.sh
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd ui/api-client/packages/sdk
      script:
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run deploy