# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: 'Angular API client Publish'

on:
  release:
    types: [prereleased, released]

jobs:
  test-publish-npm-packages:
    if: ${{ github.event.action == 'prereleased' && startsWith(github.event.release.target_commitish, 'angular-') }}
    defaults:
      run:
        working-directory: './api-client/'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: ['sdk', 'schematics', 'plugin-builders']
    steps:
      - run: echo "Dry run publish of @vcd/${{ matrix.packages }} to npm registry"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build:${{ matrix.packages }} --if-present
      - run: npm publish dist/vcd/${{ matrix.packages }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-npm-packages:
    if: ${{ github.event.action == 'released' && startsWith(github.event.release.target_commitish, 'angular-') }}
    defaults:
      run:
        working-directory: './api-client/'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: ['sdk', 'schematics', 'plugin-builders']
    steps:
      - run: echo "Publish of @vcd/${{ matrix.packages }} to npm registry"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build:${{ matrix.packages }} --if-present
      - run: npm publish dist/vcd/${{ matrix.packages }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
